### ISSUE TITLE
phase bridge get slow down

### ISSUE THREAD

**Issue by aviegdown** [sk7725/TimeControl#11]
i found that phase bridge (conveyor and conduit) are getting slow down rather than speed up, tested on campaign and custom game. mindustry v122    

1x speed
![mindustry12](https://user-images.githubusercontent.com/72583750/103144073-cf430400-4755-11eb-8588-956fe3871c1c.png)
![mindustry11](https://user-images.githubusercontent.com/72583750/103144075-d66a1200-4755-11eb-9716-1de575258507.png)

4x speed
![mindustry21](https://user-images.githubusercontent.com/72583750/103144077-e2ee6a80-4755-11eb-8eb4-859a2ef725ae.png)
![mindustry22](https://user-images.githubusercontent.com/72583750/103144079-e7b31e80-4755-11eb-8597-831d501d2cd3.png)

**Comment by sk7725** [comment]
they, along with plastanium conveyors are very sensitive to fps, and timecontrol essentially halves/quarters the fps because there are double/quadruple calculations each frame. So, unless you are on a device which is capable of a max fps of 240, it will be affected. (Which is probably why Anuke did not add this feature at the first place)

Basically, the rule of thumb is, anything that gets affected by lag is affected by the time controller.
